spring:
  datasource:
    url: jdbc:mysql://${rds.hostname}:${rds.port}/${rds.dbname}
    username: ${rds.username}
    password: ${rds.password}
    driver-class-name: ${rds.driver}

  jpa:
    #    show-sql: true
    properties:
      hibernate.hbm2ddl.auto: update
    defer-datasource-initialization: true

logging.level:
  org.hibernate.SQL: debug

server:
  port: 5000